config/routes.rb
Rails.application.routes.draw do
 
  root 'events#index'
  devise_for :users
 
  resources :events, only: [:show, :new, :create, :index, :edit, :destroy] do
    resources :pictures, only: [:create]
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :participations, only: [:new, :create, :index]
  resources :charges

  namespace :admin do
    root 'admin#index'
    resources :users, only: [:index]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :confirmation_send

  belongs_to :user
  belongs_to :event

  validates :stripe_customer_id, uniqueness: true

  def confirmation_send
    AttendanceMailer.attendee_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :manager, class_name: "User", required: false
  has_many :attendances
  has_many :users, through: :attendances
  has_one_attached :picture
  
  validate :duration_modulo_5
  validate :start_date_cannot_be_in_the_past

  validates :start_date, presence: true 
   
  validates :duration, presence: true
  
  validates :description, presence: true, length: { in: 20..1000, message: "description need 20 car. min and 1000 car. max"} 
  
  validates :title, presence: true, length: { in: 5..140, message: "title need 5 car. min and 140 car. max"} 
  
  validates :price, presence: true, numericality: { in: 1..1000, }
  
  validates :location, presence: true

  # variable pour afficher date/heure de fin pour view events/show 
  def end_date
		return (self.start_date + self.duration*60)
  end
 
  private
  def start_date_cannot_be_in_the_past
    if start_date < Time.now
      errors.add(:start_date, 'The start_date can not in the past !')
    end
  end

  def duration_modulo_5
    if !(duration % 5 == 0 && duration >= 5)
      errors.add(:duration, 'Must be a multiple of 5')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_one_attached :avatar
  has_many :attendances
  has_many :events, through: :attendances
  has_many :manager, foreign_key: 'manager_id', class_name: "Event"

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end
 

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  
  def index
    @users = User.all
  end
end

app/controllers/admin/application_controller.rb
class Admin::Controller < ApplicationController
    before_action :authenticate_user!
    before_action :is_admin?
    layout "admin"
    
    private
  
    def is_admin?
      unless current_user.is_admin
      flash[:danger] = "Tu n'es pas un admin"
         redirect_to root_path
      end
    end
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    def index
      @users = User.all
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # une fois payé retour sur l'event
  # after_create: faire attendance.create (avec event.id, current_user.id et strip number)
  
  def new
    @event = Event.find(params[:id])
  end
  
  def create
    @event = Event.find(params[:id])
    # Amount in cents
    @amount = @event.price * 100
    
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })

    a = Attendance.create(stripe_customer_id: customer.id, user: current_user, event: @event)
	  puts "*"*100
	  puts a
    puts "*"*100
    
    if a != nil
      flash[:success] = "Vous êtes inscrits"
      redirect_to event_path(id: @event.id)
    else 
      flash[:danger] = "Un problème lors votre inscritpion est survenue"
      redirect_to new_charge_path(id: @event.id)
    end

  

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]
  
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create

    @event = Event.new('title' => params[:title], 
      'description' => params[:description],
      'duration' => params[:duration],
      'start_date' => params[:start_date],
      'price' => params[:price],
      'location' => params[:location],
      'manager_id' => current_user.id) #à revoir pour heroku, fonctionne en local
    
    # J'ajoute une image 
    #@event.picture.attach(params[:picture])
    
    if @event.save
      puts "The event was succesfully saved !"
      flash[:success] = "Evènement créé !"
      redirect_to '/'
    else
      puts "Error : create problem"
      flash[:danger] = "Erreur dans la création de l'évènement (date passée ou durée pas multiple de 5) !"
      render '/events/new'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(
      start_date: params[:start_date],
      title: params[:title],
      duration: params[:duration],
      price: params[:price],
      description: params[:description]
    )
      flash[:success] = "L'événement a bien été modifié !"
      redirect_to @event
    else
      flash[:error] = "L'événement n'a pas pu être mis à jour !"
      redirect_to @event
    end
end

  def edit
    
  end

  def new
    @event = Event.new
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  #mettre test si il peut s'inscrire
  
  def new
    @event = Event.find(params[:id])
  end
  
  def create
    @event = Event.find(params[:id])
    puts "*" * 50
    puts @event.id
    puts current_user.id
    puts "*" * 50
    a = Attendance.create(stripe_customer_id: "test pour stripe",user: current_user, event: @event)

  	flash[:success] = "Vous êtes inscrits à l'évènement"
    redirect_to event_path(id: @event.id)
  end

  def index
    #@event = Event.find(params[:id])
    @attendees = Attendance.where(event_id: @event.id) #pour test event_id = 75
    puts "*" * 50
    puts @event.id
    puts current_user.id
    puts @attendees.inspect
    puts "*" * 50
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @event = User.find(params[:event_id])
    @event.picture.attach(params[:picture])
    #redirect_to(event_path(@event))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_adequate_user?, only: [:show]

  def show
    @user = User.find(params['id'])
    @user_events = Event.where(manager: @user.id)
  end

  private

  def is_adequate_user?
  	unless current_user == User.find(params['id'])
  		flash[:danger] = "Tssss, tu peux pas accéder à la page d'un autre utilisateur"
  		redirect_to user_path(current_user.id)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container-fluid">
    <h1 class="text-center">Gestion des utilisateurs </h1>
    
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>E-mail</th>
                <th>Inscrit le</th>
                <th>Mis-à-jour le</th>
                <th>Admin</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
        <% @users.each do |user|%>
            <tr>
                <td><%= user.last_name %></td>
                <td><%= user.first_name %></td>
                <td><%= user.email %></td>
                <td><%= user.created_at.strftime("%d %m %Y à %HH:%MM" ) %></td>
                <td><%= user.updated_at.strftime("%d %m %Y à %HH:%MM") %></td>
                <td>
                    <%= "Oui" if user.is_admin %>
                </td> 
                <td><%= link_to 'Infos',user_path(user.id),  class: "btn btn-info" %></td>
                <td><%= link_to 'Modifier', edit_user_registration_path(user.id), class: "btn btn-primary" %></td> 
                <td><%= link_to 'Supprimer',  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>


 

app/views/admin/users/users.html.erb
<h1>Coucou user admin</h1>

app/views/charges/create.html.erb
<h2>Merci, vous avez payé : <strong><%= @amount/100 %>€</strong>! pour votre inscription</h2>
<% puts @event.inspect%>
<%= link_to 'Finaliser votre inscription', new_participation_path(id: @event.id), :class => 'btn btn-primary' %>

app/views/charges/new.html.erb
<h1>charges#new</h1>
<h4>Vous allez procéder au paiement</h4>

Pour l'évènement : <% @event.title %> à <%@event.location%> le <%@event.start_date%>
<%= form_tag charges_path(id: @event.id) do %>

  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Montant: <%= "#{@event.price} €" %> </span>
    </label>
    <%#= label_tag 'Montant : ' %>
    <%#= text_field_tag 'amount', @amount%>

  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @event.price * 100 %>"
          data-currency="eur"
          data-locale="auto"></script>
<% end %>

app/views/events/destroy.html.erb
<h1>event#destroy</h1>

app/views/events/edit.html.erb
<h1>Events#edit</h1>

<%= link_to "Delete Event", event_path, data: {confirm: "Are you sure?"}, method: "delete", class: "btn btn-danger mb-0 my-3" %>

<%= form_tag url_for(action: 'update'), method: "patch" do %>

  <div class="form-group">
    <%= label_tag(:title, "Titre:") %>
    <%= text_field_tag(:title,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:description, "Description:") %>
    <%= text_area_tag(:description,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:location, "Localisation:") %>
    <%= text_field_tag(:location, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:price, "Prix:") %>
    <small> (Doit être un compris entre 1 et 1000 euros)</small>
    <%= text_field_tag(:price, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:start_date, "Début:") %>
    <%= text_field_tag(:start_date, Time.now+1000 , :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:duration, "Durée:") %>
    <small> (Durée est multiple de 5 min.)</small>
    <%= text_field_tag(:duration,"",:class => 'form-control')%>
  </div>

		<div class="col-sm-12 d-flex justify-content-center  m-3">
			<%= submit_tag("Modifier l'évènement", :class => "btn btn-primary") %>
		</div>

<% end %>

app/views/events/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Derniers évènements !</h1>
    <% if user_signed_in? %>
      <h1 class="display-6">Bienvenue <%= current_user.email %> ! </h1>
    <% else %>
      <h1 class="display-6">Bienvenue ! </h1>
    <% end %>  
    <p class="lead">Inscrivez-vous vite et rejoingnez la communauté...</p>
      <p>Si tu as envie d'en créer un, fonce.</p>
        <%=link_to "Créer un événement", new_event_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>


<div class="card-columns border-info container ">

<% Event.all.order(start_date: :asc).each do |event| %>
    <div class="card border-info text-white bg-info mb-1">
      <div class="card-header bg-light text-danger">
        <small>Quand : <%=event.start_date.strftime("%d %m %Y")%></small>
      </div>
      <div class="card-body bg-info">
        <%= link_to event_path(event.id), class:"list-group-item list-group-item-action"  do %>
        
          <h5 class="card-title"><%=event.title %></h5><br/>
          <small>Lieu : <%=event.location%></small>

      </div>
    </div>
  <% end %>
<% end %>

</div>

app/views/events/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Créer un event</h1>
  </div>
</div>

<h3>Photo de l'évènement</h3>
<%if @event.picture.attached?%>
  <%= image_tag @event.picture, alt: 'photo event' %>
<%else%>
  <p>=== Mettre une illustration pour l'évènement après sa création ===</p>
<%end%>

<%= form_tag url_for(action: 'create'), method: "post" do %>

  <div class="form-group">
    <%= label_tag(:title, "Titre:") %>
    <%= text_field_tag(:title,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:description, "Description:") %>
    <%= text_area_tag(:description,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:location, "Localisation:") %>
    <%= text_field_tag(:location, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:price, "Prix:") %>
    <small> (Doit être un compris entre 1 et 1000 euros)</small>
    <%= text_field_tag(:price, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:start_date, "Début:") %>
    <%= text_field_tag(:start_date, Time.now+1000 , :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:duration, "Durée:") %>
    <small> (Durée est multiple de 5 min.)</small>
    <%= text_field_tag(:duration,"",:class => 'form-control')%>
  </div>

		<div class="col-sm-12 d-flex justify-content-center  m-3">
			<%= submit_tag("Créer l'évènement", :class => "btn btn-primary") %>
		</div>

<% end %>

app/views/events/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">Plus d'infos sur l'évènement</p>
    <h1 class="display-4 text-success"><%=@event.title %></h1>
  </div>
</div>

<div class="card-columns border-info container bg-info">

  <p><strong class="text-warning">Titre : </strong>   <%=@event.title %><br/>
  <strong class="text-warning">Description: </strong> <%=@event.description %><br/>
  <strong class="text-warning">Date : </strong>       <%=@event.start_date.strftime("%d/%m/%Y") %> à <%=@event.start_date.strftime("%H:%M")%><br/>
  <strong class="text-warning">Durée : </strong>      <%=@event.duration %> min.<br/>
  <strong class="text-warning">Fin à : </strong>       <%=@event.end_date.strftime("%H:%M") %><br/>
  <strong class="text-warning">Lieu : </strong>       <%=@event.location%><br/>
  <strong class="text-warning">Prix : </strong>       <%=@event.price%> €<br/>
        Inscrit(s) : <%=@event.users.count%><br/>
        Event géré par : <%=(@event.manager_id!=nil)?(@event.manager.email):("N/A") %>
  </p>
</div>
<br/><br/>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 offset-md-3">
    <!-- faire test si user déjà inscrit et mettre bouton pour destroy -->
      <% if current_user.id == @event.manager_id # user_signed_in? && %>  
        <%= link_to 'Mon espace événement', edit_event_path(@event), class: "btn btn-warning btn-lg"  %>
      <% elsif @event.price.to_i != 0%>
          <!-- inscription payante -->
          <%=link_to "Rejoindre l'évènement", new_charge_path(id: @event.id), class: "btn btn-primary btn-lg" %>
        <% else %>
          <!-- inscription gratuite -->
          <%=link_to "S'incrire à l'évènement", new_participation_path, class: "btn btn-primary btn-lg" %>
      <%end%>
    </div>
  </div>
</div>

app/views/participations/create.html.erb
<h1>participations#create</h1>

app/views/participations/index.html.erb
<h1> index participation </h1>

<%=link_to "Editer l'évènement", edit_event_path(@attendees[0].event_id), class: "btn btn-primary btn-lg" %>
<%=link_to "Supprimer l'évènement", event_path(@attendees[0].event_id), class: "btn btn-primary btn-lg" %>
<% @attendees.each do |client| %>
<div class="card border-info text-white bg-info mb-5">
    <div class="card-header bg-light text-danger">
    <small>Participants : <%=client.user.email%></small>
    </div>
    <div class="card-body bg-info">
        <h5 class="card-title"><%=client.user.first_name %></h5>
        <h5 class="card-title"><%=client.user.last_name %></h5>
    </div>
</div>
  
<% end %>

app/views/participations/new.html.erb
<h1>Participations#new</h1>

Je vous inscrit à <% @event.title %>

<%= link_to "Oui, je m'inscris", participations_path(id: @event.id), :class => 'btn btn-primary' %>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Profil utilisateur de:</h1>
  <h1 class="display-4"><%= @user.first_name%> <%= @user.last_name%></h1>
  <p class="lead"><%= @user.description%></p>
  <p>Clique pour crééer un événement</p>
  <%=link_to "Créer un événement", new_event_path, class: "btn btn-primary btn-lg" %>
  <%=link_to "Changer ton mot de passe", edit_user_registration_path, class: "btn btn-primary btn-lg" %>
	<%if current_user.is_admin? %>
		<%=link_to "Accès admin", admin_users_path, class: "btn btn-warning btn-lg" %>
	<%end%>
</div>

<div class="container d-flex justify-content-center">
	<div class="row">
		<div class="col-sm-12 d-flex justify-content-center m-3">
			<h2>Ce que je sais de <%=@user.first_name %> <%=@user.last_name %></h2>
		</div>
		<div class="col-sm-12 d-flex justify-content-center">
			<table class="table table-bordered">
			  <thead>
			    <tr>
			      <th scope="col">First name</th>
			      <th scope="col">Last name</th>
			      <th scope="col">Email address</th>
			    </tr>
			  </thead>
			  <tbody>
			    <tr>
			      <td><%=@user.first_name %></td>
			      <td><%=@user.last_name %></td>
			      <td><%=@user.email %></td>
			    </tr>
			    <tr>
			  </tbody>
			</table>
		</div>
		<div class="col-sm-12 d-flex justify-content-center">
			<%= link_to edit_user_registration_path(id: @user.id) do %>
			<button class="btn btn-icon btn-3 btn-primary" type="button">
				<span class="btn-inner--icon"><i class="ni ni-bag-17"></i></span>
			   <span class="btn-inner--text">Editer mes informations</span>
			</button>
			<%end%>
		</div>
	</div>
</div>

<div class="container d-flex justify-content-center">
	<div class="row">
		<div class="col-sm-12 d-flex justify-content-center m-3">
			<h2>Je suis inscrit aux events suivants</h2>
		</div>
		<div class="col-sm-12 d-flex justify-content-center">
			<table class="table table-bordered">
			  <thead>
			    <tr>
			      <th scope="col">Evénement</th>
			      <th scope="col">Page de l'événément</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% @user.events.each do |event| %>
			    <tr>
			      <td><%=event.title %></td>
			      <td><%= link_to 'Détail', event_path(event.id), class: 'btn btn-secondary bg-info' %></td>
			    </tr>
			    <tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
	</div>
</div>

<div class="container d-flex justify-content-center">
	<div class="row">
		<div class="col-sm-12 d-flex justify-content-center m-3">
			<h2>Mes événements en tant qu'organisateur</h2>
		</div>
		<div class="col-sm-12 d-flex justify-content-center">
			<table class="table table-bordered">
			  <thead>
			    <tr>
			      <th scope="col">Evénement</th>
			      <th scope="col">Page de l'événément</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% @user_events.each do |event| %>
			    <tr>
			      <td><%=event.title %></td>
			      <td><%= link_to "Voir plus", event_path(event.id) %></td>
			    </tr>
			    <tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
	</div>
</div>


<%if @user.avatar.attached?%>
  <%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
<%end%>

<h3>Changer de photo de profil ?</h3>
<%= form_tag user_avatars_path(@user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "Mettre à jour" %>
<% end %>